services:
  mysql:
    container_name: mysql_container
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: '!@Skdud340'
      MYSQL_DATABASE: jenkinsdb
    restart: always

  backend:
    container_name: test_container
    build: .
    ports:
      - 8081:8080
    depends_on:
      - mysql
    restart: always