services:
  jenkins:
    container_name: jenkins_container
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    user: root
    ports:
      - 7777:8080
    volumes:
      - jenkins_data:/var/jenkins_home  # Jenkins 데이터 볼륨
      - /var/run/docker.sock:/var/run/docker.sock  # Docker 데몬 소켓 공유
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock  # Docker 소켓을 환경 변수로 설정

  mysql:
    container_name: mysql_container
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: '!@Skdud340'
      MYSQL_DATABASE: jenkinsdb
    volumes:
      - mysql_data:/var/lib/mysql  # MySQL 데이터 디렉토리 볼륨
    restart: always

volumes:
  jenkins_data:
  mysql_data:
