services:
  jenkins:
    container_name: jenkins_container
    image: jenkins/jenkins:jdk17
    restart: unless-stopped
    user: root
    ports:
      - 7777:8080
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: >
      /bin/bash -c "apt-get update && 
                    apt-get install -y git openssh-client docker.io &&
                    exec /usr/local/bin/jenkins.sh"

  mysql:
    container_name: mysql_container
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: '!@Skdud340'
      MYSQL_DATABASE: jenkinsdb
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  redis:
    container_name: redis_container
    image: redis
    ports:
      - 6380:6379
    restart: always
    volumes:
      - redis_data:/data

  mongodb:
    container_name: mongodb_container
    image: mongo
    ports:
      - 27018:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    container_name: backend_container
    build: .
    ports:
      - 8081:8080
    restart: always
    depends_on:
      - mysql
      - redis
      - mongodb

volumes:
  jenkins_data:
  mysql_data:
  redis_data:
  mongo_data:
